# Foursquare configuration for MultiPass
client_id:     ''
client_secret: ''
token_params:
  redirect_uri: 'http://yoursite.com/foursquare/callback'
authorize_options:
  redirect_uri: 'http://yoursite.com/foursquare/callback'
